git-hyperfine: stop calling 'basename'
One less thing to slow us down, and it's not really needed at all.

diff --git a/git-hyperfine b/git-hyperfine
--- a/git-hyperfine
+++ b/git-hyperfine
@@ -3,7 +3,6 @@
 # git-hyperfine: thing wrapper around hyperfine(1). See --help output
 # below.
 
-ghf=$(basename "$0")
 debug=
 debug() {
 	if test -n "$debug"
@@ -359,13 +358,13 @@ fi
 ## Options sanity check
 if test -z "$saw_rev"
 then
-	echo "$ghf needs a -L rev <rev>..., e.g. -L rev HEAD~1,HEAD~0" >&2
+	echo "git-hyperfine needs a -L rev <rev>..., e.g. -L rev HEAD~1,HEAD~0" >&2
 	exit 1
 fi
 
 if test -n "$command_name"
 then
-	echo "$ghf can't take your -n|--command-name $command_name. It needs it" >&2
+	echo "$git-hyperfine can't take your -n|--command-name $command_name. It needs it" >&2
 	exit 1
 fi
 
